{% set version = '0.6' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-tagcloud
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tagcloud_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tagcloud/tagcloud_{{ version }}.tar.gz
  sha256: 94db4eb51471d3ffbc91704337645e5b418c613fad5d9369a7f2229b0480f913

build:
  number: 6
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('m2w64_cxx') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-rcolorbrewer               # [build_platform != target_platform]
    - r-rcpp >=0.9.4               # [build_platform != target_platform]
  host:
    - r-base
    - r-rcolorbrewer
    - r-rcpp >=0.9.4
  run:
    - r-base
    - r-rcolorbrewer
    - r-rcpp >=0.9.4

test:
  commands:
    - $R -e "library('tagcloud')"           # [not win]
    - "\"%R%\" -e \"library('tagcloud')\""  # [win]

about:
  home: http://logfc.wordpress.com
  license: GPL-2.0-or-later
  summary: Generating Tag and Word Clouds.
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - PertuyF

# Package: tagcloud
# Type: Package
# Title: Tag Clouds
# Version: 0.6
# Date: 2015-07-02
# Author: January Weiner
# Maintainer: January Weiner <january.weiner@gmail.com>
# Description: Generating Tag and Word Clouds.
# License: GPL (>= 2)
# LazyLoad: yes
# Depends: Rcpp (>= 0.9.4)
# Imports: RColorBrewer
# Suggests: extrafont,knitr
# VignetteBuilder: knitr
# LinkingTo: Rcpp
# URL: http://logfc.wordpress.com
# NeedsCompilation: yes
# Packaged: 2015-07-03 07:23:26.877 UTC; january
# Repository: CRAN
# Date/Publication: 2015-07-03 11:17:02
